# Generated by Django 3.2.4 on 2021-06-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('price', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=10)),
                ('market_cap', models.CharField(max_length=200)),
            ],
        ),
    ]
