# Generated by Django 3.2.4 on 2021-06-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20210613_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptodata',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
